//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sincronización.FacturasLista {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FacturasLista_Binding", Namespace="urn:microsoft-dynamics-schemas/page/facturaslista")]
    public partial class FacturasLista_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FacturasLista_Service() {
            this.Url = global::Sincronización.Properties.Settings.Default.Sincronización_FacturasLista_FacturasLista_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/facturaslista:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("FacturasLista")]
        public FacturasLista Read(int Entry_No) {
            object[] results = this.Invoke("Read", new object[] {
                        Entry_No});
            return ((FacturasLista)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(int Entry_No) {
            this.ReadAsync(Entry_No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(int Entry_No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Entry_No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/facturaslista:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("FacturasLista")]
        public FacturasLista ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((FacturasLista)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/facturaslista:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public FacturasLista[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] FacturasLista_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((FacturasLista[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(FacturasLista_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(FacturasLista_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/facturaslista:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/facturaslista:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/facturaslista:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref FacturasLista FacturasLista) {
            object[] results = this.Invoke("Update", new object[] {
                        FacturasLista});
            FacturasLista = ((FacturasLista)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(FacturasLista FacturasLista) {
            this.UpdateAsync(FacturasLista, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(FacturasLista FacturasLista, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        FacturasLista}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/facturaslista:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/facturaslista", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref FacturasLista[] FacturasLista_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        FacturasLista_List});
            FacturasLista_List = ((FacturasLista[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(FacturasLista[] FacturasLista_List) {
            this.UpdateMultipleAsync(FacturasLista_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(FacturasLista[] FacturasLista_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        FacturasLista_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/facturaslista")]
    public partial class FacturasLista {
        
        private string keyField;
        
        private System.DateTime posting_DateField;
        
        private bool posting_DateFieldSpecified;
        
        private Document_Type document_TypeField;
        
        private bool document_TypeFieldSpecified;
        
        private string document_NoField;
        
        private string bill_NoField;
        
        private Document_Situation document_SituationField;
        
        private bool document_SituationFieldSpecified;
        
        private Document_Status document_StatusField;
        
        private bool document_StatusFieldSpecified;
        
        private string customer_NoField;
        
        private string message_to_RecipientField;
        
        private string descriptionField;
        
        private string global_Dimension_1_CodeField;
        
        private string global_Dimension_2_CodeField;
        
        private string iC_Partner_CodeField;
        
        private string salesperson_CodeField;
        
        private string currency_CodeField;
        
        private decimal original_AmountField;
        
        private bool original_AmountFieldSpecified;
        
        private decimal original_Amt_LCYField;
        
        private bool original_Amt_LCYFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private decimal amount_LCYField;
        
        private bool amount_LCYFieldSpecified;
        
        private decimal remaining_AmountField;
        
        private bool remaining_AmountFieldSpecified;
        
        private decimal remaining_Amt_LCYField;
        
        private bool remaining_Amt_LCYFieldSpecified;
        
        private Bal_Account_Type bal_Account_TypeField;
        
        private bool bal_Account_TypeFieldSpecified;
        
        private string bal_Account_NoField;
        
        private System.DateTime due_DateField;
        
        private bool due_DateFieldSpecified;
        
        private System.DateTime pmt_Discount_DateField;
        
        private bool pmt_Discount_DateFieldSpecified;
        
        private System.DateTime pmt_Disc_Tolerance_DateField;
        
        private bool pmt_Disc_Tolerance_DateFieldSpecified;
        
        private decimal original_Pmt_Disc_PossibleField;
        
        private bool original_Pmt_Disc_PossibleFieldSpecified;
        
        private decimal remaining_Pmt_Disc_PossibleField;
        
        private bool remaining_Pmt_Disc_PossibleFieldSpecified;
        
        private decimal max_Payment_ToleranceField;
        
        private bool max_Payment_ToleranceFieldSpecified;
        
        private decimal pmt_Disc_Given_LCYField;
        
        private bool pmt_Disc_Given_LCYFieldSpecified;
        
        private string payment_Method_CodeField;
        
        private string cod_banco_prevision_cobroField;
        
        private bool openField;
        
        private bool openFieldSpecified;
        
        private string on_HoldField;
        
        private string user_IDField;
        
        private string source_CodeField;
        
        private string reason_CodeField;
        
        private bool reversedField;
        
        private bool reversedFieldSpecified;
        
        private int reversed_by_Entry_NoField;
        
        private bool reversed_by_Entry_NoFieldSpecified;
        
        private int reversed_Entry_NoField;
        
        private bool reversed_Entry_NoFieldSpecified;
        
        private int entry_NoField;
        
        private bool entry_NoFieldSpecified;
        
        private bool exported_to_Payment_FileField;
        
        private bool exported_to_Payment_FileFieldSpecified;
        
        private string direct_Debit_Mandate_IDField;
        
        private int transaction_NoField;
        
        private bool transaction_NoFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Posting_Date {
            get {
                return this.posting_DateField;
            }
            set {
                this.posting_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Posting_DateSpecified {
            get {
                return this.posting_DateFieldSpecified;
            }
            set {
                this.posting_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Document_Type Document_Type {
            get {
                return this.document_TypeField;
            }
            set {
                this.document_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_TypeSpecified {
            get {
                return this.document_TypeFieldSpecified;
            }
            set {
                this.document_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Document_No {
            get {
                return this.document_NoField;
            }
            set {
                this.document_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Bill_No {
            get {
                return this.bill_NoField;
            }
            set {
                this.bill_NoField = value;
            }
        }
        
        /// <remarks/>
        public Document_Situation Document_Situation {
            get {
                return this.document_SituationField;
            }
            set {
                this.document_SituationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_SituationSpecified {
            get {
                return this.document_SituationFieldSpecified;
            }
            set {
                this.document_SituationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Document_Status Document_Status {
            get {
                return this.document_StatusField;
            }
            set {
                this.document_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_StatusSpecified {
            get {
                return this.document_StatusFieldSpecified;
            }
            set {
                this.document_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Customer_No {
            get {
                return this.customer_NoField;
            }
            set {
                this.customer_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Message_to_Recipient {
            get {
                return this.message_to_RecipientField;
            }
            set {
                this.message_to_RecipientField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Global_Dimension_1_Code {
            get {
                return this.global_Dimension_1_CodeField;
            }
            set {
                this.global_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Global_Dimension_2_Code {
            get {
                return this.global_Dimension_2_CodeField;
            }
            set {
                this.global_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string IC_Partner_Code {
            get {
                return this.iC_Partner_CodeField;
            }
            set {
                this.iC_Partner_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Salesperson_Code {
            get {
                return this.salesperson_CodeField;
            }
            set {
                this.salesperson_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Currency_Code {
            get {
                return this.currency_CodeField;
            }
            set {
                this.currency_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Original_Amount {
            get {
                return this.original_AmountField;
            }
            set {
                this.original_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Original_AmountSpecified {
            get {
                return this.original_AmountFieldSpecified;
            }
            set {
                this.original_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Original_Amt_LCY {
            get {
                return this.original_Amt_LCYField;
            }
            set {
                this.original_Amt_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Original_Amt_LCYSpecified {
            get {
                return this.original_Amt_LCYFieldSpecified;
            }
            set {
                this.original_Amt_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount_LCY {
            get {
                return this.amount_LCYField;
            }
            set {
                this.amount_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Amount_LCYSpecified {
            get {
                return this.amount_LCYFieldSpecified;
            }
            set {
                this.amount_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Remaining_Amount {
            get {
                return this.remaining_AmountField;
            }
            set {
                this.remaining_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Remaining_AmountSpecified {
            get {
                return this.remaining_AmountFieldSpecified;
            }
            set {
                this.remaining_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Remaining_Amt_LCY {
            get {
                return this.remaining_Amt_LCYField;
            }
            set {
                this.remaining_Amt_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Remaining_Amt_LCYSpecified {
            get {
                return this.remaining_Amt_LCYFieldSpecified;
            }
            set {
                this.remaining_Amt_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Bal_Account_Type Bal_Account_Type {
            get {
                return this.bal_Account_TypeField;
            }
            set {
                this.bal_Account_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bal_Account_TypeSpecified {
            get {
                return this.bal_Account_TypeFieldSpecified;
            }
            set {
                this.bal_Account_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Bal_Account_No {
            get {
                return this.bal_Account_NoField;
            }
            set {
                this.bal_Account_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Due_Date {
            get {
                return this.due_DateField;
            }
            set {
                this.due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Due_DateSpecified {
            get {
                return this.due_DateFieldSpecified;
            }
            set {
                this.due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Pmt_Discount_Date {
            get {
                return this.pmt_Discount_DateField;
            }
            set {
                this.pmt_Discount_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pmt_Discount_DateSpecified {
            get {
                return this.pmt_Discount_DateFieldSpecified;
            }
            set {
                this.pmt_Discount_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Pmt_Disc_Tolerance_Date {
            get {
                return this.pmt_Disc_Tolerance_DateField;
            }
            set {
                this.pmt_Disc_Tolerance_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pmt_Disc_Tolerance_DateSpecified {
            get {
                return this.pmt_Disc_Tolerance_DateFieldSpecified;
            }
            set {
                this.pmt_Disc_Tolerance_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Original_Pmt_Disc_Possible {
            get {
                return this.original_Pmt_Disc_PossibleField;
            }
            set {
                this.original_Pmt_Disc_PossibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Original_Pmt_Disc_PossibleSpecified {
            get {
                return this.original_Pmt_Disc_PossibleFieldSpecified;
            }
            set {
                this.original_Pmt_Disc_PossibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Remaining_Pmt_Disc_Possible {
            get {
                return this.remaining_Pmt_Disc_PossibleField;
            }
            set {
                this.remaining_Pmt_Disc_PossibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Remaining_Pmt_Disc_PossibleSpecified {
            get {
                return this.remaining_Pmt_Disc_PossibleFieldSpecified;
            }
            set {
                this.remaining_Pmt_Disc_PossibleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Max_Payment_Tolerance {
            get {
                return this.max_Payment_ToleranceField;
            }
            set {
                this.max_Payment_ToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Max_Payment_ToleranceSpecified {
            get {
                return this.max_Payment_ToleranceFieldSpecified;
            }
            set {
                this.max_Payment_ToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Pmt_Disc_Given_LCY {
            get {
                return this.pmt_Disc_Given_LCYField;
            }
            set {
                this.pmt_Disc_Given_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pmt_Disc_Given_LCYSpecified {
            get {
                return this.pmt_Disc_Given_LCYFieldSpecified;
            }
            set {
                this.pmt_Disc_Given_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Method_Code {
            get {
                return this.payment_Method_CodeField;
            }
            set {
                this.payment_Method_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Cod_banco_prevision_cobro {
            get {
                return this.cod_banco_prevision_cobroField;
            }
            set {
                this.cod_banco_prevision_cobroField = value;
            }
        }
        
        /// <remarks/>
        public bool Open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpenSpecified {
            get {
                return this.openFieldSpecified;
            }
            set {
                this.openFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string On_Hold {
            get {
                return this.on_HoldField;
            }
            set {
                this.on_HoldField = value;
            }
        }
        
        /// <remarks/>
        public string User_ID {
            get {
                return this.user_IDField;
            }
            set {
                this.user_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Source_Code {
            get {
                return this.source_CodeField;
            }
            set {
                this.source_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Reason_Code {
            get {
                return this.reason_CodeField;
            }
            set {
                this.reason_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Reversed {
            get {
                return this.reversedField;
            }
            set {
                this.reversedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReversedSpecified {
            get {
                return this.reversedFieldSpecified;
            }
            set {
                this.reversedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Reversed_by_Entry_No {
            get {
                return this.reversed_by_Entry_NoField;
            }
            set {
                this.reversed_by_Entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reversed_by_Entry_NoSpecified {
            get {
                return this.reversed_by_Entry_NoFieldSpecified;
            }
            set {
                this.reversed_by_Entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Reversed_Entry_No {
            get {
                return this.reversed_Entry_NoField;
            }
            set {
                this.reversed_Entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reversed_Entry_NoSpecified {
            get {
                return this.reversed_Entry_NoFieldSpecified;
            }
            set {
                this.reversed_Entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Entry_No {
            get {
                return this.entry_NoField;
            }
            set {
                this.entry_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Entry_NoSpecified {
            get {
                return this.entry_NoFieldSpecified;
            }
            set {
                this.entry_NoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Exported_to_Payment_File {
            get {
                return this.exported_to_Payment_FileField;
            }
            set {
                this.exported_to_Payment_FileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Exported_to_Payment_FileSpecified {
            get {
                return this.exported_to_Payment_FileFieldSpecified;
            }
            set {
                this.exported_to_Payment_FileFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Direct_Debit_Mandate_ID {
            get {
                return this.direct_Debit_Mandate_IDField;
            }
            set {
                this.direct_Debit_Mandate_IDField = value;
            }
        }
        
        /// <remarks/>
        public int Transaction_No {
            get {
                return this.transaction_NoField;
            }
            set {
                this.transaction_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Transaction_NoSpecified {
            get {
                return this.transaction_NoFieldSpecified;
            }
            set {
                this.transaction_NoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/facturaslista")]
    public enum Document_Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Payment,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        Credit_Memo,
        
        /// <remarks/>
        Finance_Charge_Memo,
        
        /// <remarks/>
        Reminder,
        
        /// <remarks/>
        Refund,
        
        /// <remarks/>
        Bill,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/facturaslista")]
    public enum Document_Situation {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Posted_BG_PO,
        
        /// <remarks/>
        Closed_BG_PO,
        
        /// <remarks/>
        BG_PO,
        
        /// <remarks/>
        Cartera,
        
        /// <remarks/>
        Closed_Documents,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/facturaslista")]
    public enum Document_Status {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Honored,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Redrawn,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/facturaslista")]
    public enum Bal_Account_Type {
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Customer,
        
        /// <remarks/>
        Vendor,
        
        /// <remarks/>
        Bank_Account,
        
        /// <remarks/>
        Fixed_Asset,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/facturaslista")]
    public partial class FacturasLista_Filter {
        
        private FacturasLista_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public FacturasLista_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/facturaslista")]
    public enum FacturasLista_Fields {
        
        /// <remarks/>
        Posting_Date,
        
        /// <remarks/>
        Document_Type,
        
        /// <remarks/>
        Document_No,
        
        /// <remarks/>
        Bill_No,
        
        /// <remarks/>
        Document_Situation,
        
        /// <remarks/>
        Document_Status,
        
        /// <remarks/>
        Customer_No,
        
        /// <remarks/>
        Message_to_Recipient,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Global_Dimension_1_Code,
        
        /// <remarks/>
        Global_Dimension_2_Code,
        
        /// <remarks/>
        IC_Partner_Code,
        
        /// <remarks/>
        Salesperson_Code,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        Original_Amount,
        
        /// <remarks/>
        Original_Amt_LCY,
        
        /// <remarks/>
        Amount,
        
        /// <remarks/>
        Amount_LCY,
        
        /// <remarks/>
        Remaining_Amount,
        
        /// <remarks/>
        Remaining_Amt_LCY,
        
        /// <remarks/>
        Bal_Account_Type,
        
        /// <remarks/>
        Bal_Account_No,
        
        /// <remarks/>
        Due_Date,
        
        /// <remarks/>
        Pmt_Discount_Date,
        
        /// <remarks/>
        Pmt_Disc_Tolerance_Date,
        
        /// <remarks/>
        Original_Pmt_Disc_Possible,
        
        /// <remarks/>
        Remaining_Pmt_Disc_Possible,
        
        /// <remarks/>
        Max_Payment_Tolerance,
        
        /// <remarks/>
        Pmt_Disc_Given_LCY,
        
        /// <remarks/>
        Payment_Method_Code,
        
        /// <remarks/>
        Cod_banco_prevision_cobro,
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        On_Hold,
        
        /// <remarks/>
        User_ID,
        
        /// <remarks/>
        Source_Code,
        
        /// <remarks/>
        Reason_Code,
        
        /// <remarks/>
        Reversed,
        
        /// <remarks/>
        Reversed_by_Entry_No,
        
        /// <remarks/>
        Reversed_Entry_No,
        
        /// <remarks/>
        Entry_No,
        
        /// <remarks/>
        Exported_to_Payment_File,
        
        /// <remarks/>
        Direct_Debit_Mandate_ID,
        
        /// <remarks/>
        Transaction_No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FacturasLista Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FacturasLista)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FacturasLista Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FacturasLista)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FacturasLista[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FacturasLista[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FacturasLista FacturasLista {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FacturasLista)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FacturasLista[] FacturasLista_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FacturasLista[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591