//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sincronización.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7047/InstanceName/WS/MAI%20AUTOPARTS%252C%20S.L./Page/Produc" +
            "toLista")]
        public string Sincronización_ProductoLista_ProductoLista_Service {
            get {
                return ((string)(this["Sincronización_ProductoLista_ProductoLista_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7047/InstanceName/WS/MAI%20AUTOPARTS%252C%20S.L./Page/Client" +
            "eLista")]
        public string Sincronización_ClienteLista_ClienteLista_Service {
            get {
                return ((string)(this["Sincronización_ClienteLista_ClienteLista_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7047/InstanceName/WS/MAI%20AUTOPARTS%252C%20S.L./Page/Client" +
            "eGrupoPrecios")]
        public string Sincronización_ClienteGrupoPrecios_ClienteGrupoPrecios_Service {
            get {
                return ((string)(this["Sincronización_ClienteGrupoPrecios_ClienteGrupoPrecios_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7047/InstanceName/WS/MAI%20AUTOPARTS%252C%20S.L./Page/Produc" +
            "toFicha")]
        public string Sincronización_ProductoFicha_ProductoFicha_Service {
            get {
                return ((string)(this["Sincronización_ProductoFicha_ProductoFicha_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7047/InstanceName/WS/MAI%20AUTOPARTS%252C%20S.L./Page/Produc" +
            "toImagen")]
        public string Sincronización_ProductoImagen_ProductoImagen_Service {
            get {
                return ((string)(this["Sincronización_ProductoImagen_ProductoImagen_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7047/InstanceName/WS/MAI%20AUTOPARTS%252C%20S.L./Page/Produc" +
            "toTraduccion")]
        public string Sincronización_ProductoTraduccion_ProductoTraduccion_Service {
            get {
                return ((string)(this["Sincronización_ProductoTraduccion_ProductoTraduccion_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7047/InstanceName/WS/MAI%20AUTOPARTS%252C%20S.L./Page/Pedido" +
            "Ficha")]
        public string Sincronización_PedidoFicha_PedidoFicha_Service {
            get {
                return ((string)(this["Sincronización_PedidoFicha_PedidoFicha_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7047/InstanceName/WS/MAI%20AUTOPARTS%252C%20S.L./Page/Factur" +
            "asLista")]
        public string Sincronización_FacturasLista_FacturasLista_Service {
            get {
                return ((string)(this["Sincronización_FacturasLista_FacturasLista_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7047/InstanceName/WS/MAI%20AUTOPARTS%252C%20S.L./Page/Produc" +
            "toCaracteristica")]
        public string Sincronización_ProductoCaracteristicas_ProductoCaracteristica_Service {
            get {
                return ((string)(this["Sincronización_ProductoCaracteristicas_ProductoCaracteristica_Service"]));
            }
        }
    }
}
